### ISSUE TITLE
compile issue on ubuntu 16.04 with cleanse

### ISSUE THREAD

**Issue by RafalSladek** [Cropdev/CropDev#5]
with command:
`/CropDev/src# make -f makefile.unix`

i am getting this error:
`g++ -c -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -Wunused-function -Wunused-variable -fpermissive -Wconversion-null -g -DBOOST_SPIRIT_THREADSAFE -I/usr/local/src/CropDev/src -I/usr/local/src/CropDev/src/obj -DUSE_UPNP=0 -DENABLE_WALLET -I/usr/local/src/CropDev/src/secp256k1/include -I/usr/local/src/CropDev/src/leveldb/include -I/usr/local/src/CropDev/src/leveldb/helpers -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/support/cleanse.d -o obj/support/cleanse.o support/cleanse.cpp
support/cleanse.cpp:13:1: fatal error: opening dependency file obj/support/cleanse.d: No such file or directory
 }
 ^
compilation terminated.
makefile.unix:201: recipe for target 'obj/support/cleanse.o' failed
make: *** [obj/support/cleanse.o] Error 1`

can you provide any instruction or a fork repo to lookup

**Comment by ubaggili** [comment]
bump - having the same issue

**Comment by RafalSladek** [comment]
I found this 
apt-get update >/dev/null 2>&1
apt install -y software-properties-common >/dev/null 2>&1
echo -e "${GREEN}Adding bitcoin PPA repository"
apt-add-repository -y ppa:bitcoin/bitcoin >/dev/null 2>&1
echo -e "Installing required packages, it may take some time to finish.${NC}"
apt-get update >/dev/null 2>&1
apt-get install -y make software-properties-common build-essential libtool autoconf libssl-dev libboost-dev libboost-chrono-dev \
libboost-filesystem-dev libboost-program-options-dev libboost-system-dev libboost-test-dev libboost-thread-dev sudo automake git \
wget pwgen curl libdb4.8-dev bsdmainutils libdb4.8++-dev libminiupnpc-dev libgmp3-dev

wget https://github.com/Cropdev/CropDev/archive/v1.0.0.1.tar.gz
tar -xvf v1.0.0.1.tar.gz
cd CropDev-1.0.0.1/src/secp256k1
chmod +x autogen.sh
./autogen.sh
./configure --enable-module-recovery
make

./tests
clear
cd ..
mkdir obj/support
mkdir obj/crypto
make -f makefile.unix

**Comment by Fibroblasto** [comment]
@RafalSladek your workaround worked also in v1.0.0.2 too, but that only compiles crowdcoind. How to compile the qt wallet?
